-----------------------------------
--  Areas ID
-----------------------------------

MISSION_SANDORIA = 0;
MISSION_BASTOK = 1;
MISSION_WINDURST = 2;
MISSION_ZILART = 3;
MISSION_TOAU = 4;
MISSION_WOTG = 5;
MISSION_COP = 6;
MISSIONASSAULT = 7;
MISSION_CAMPAIGN = 8;
MISSION_ACP = 9;

-----------------------------------
--  San d'Oria
-----------------------------------

SMASH_THE_ORCISH_SCOUTS = 0;
BAT_HUNT = 1;
SAVE_THE_CHILDREN = 2;
THE_RESCUE_DRILL = 3;
THE_DAVOI_REPORT = 4;
JOURNEY_ABROAD =  = 5;
JOURNEY_TO_BASTOK = 6;
JOURNEY_TO_WINDURST = 7;
JOURNEY_TO_BASTOK = 8;
JOURNEY_TO_WINDURST = 9;
INFILTRATE_DAVOI = 10;
THE_CRYSTAL_SPRING = 11;
APPOINTMENT_TO_JEUNO = 12;
MAGICITE_SAN_D_ORIA = 13;
THE_RUINS_OF_FEI_YIN = 14;
THE_SHADOW_LORD = 15;
LEAUTE_S_LAST_WISHES = 16;
RANPERRE_S_FINAL_REST = 17;
PRESTIGE_OF_THE_PAPSQUE = 18;
THE_SECRET_WEAPON = 19;
COMING_OF_AGE = 20;
LIGHTBRINGER = 21;
BREAKING_BARRIERS = 22;
THE_HEIR_TO_THE_LIGHT = 23;

-----------------------------------
--  Bastok
-----------------------------------

THE_ZERUHN_REPORT = 0;
GEOLOGICAL_SURVEY = 1;
FETICHISM = 2;
THE_CRYSTAL_LINE = 3;
WADING_BEASTS = 4;
THE_EMISSARY = 5;
THE_EMISSARY_SAN_D_ORIA = 6;
THE_EMISSARY_WINDURST = 7;
THE_EMISSARY_SAN_D_ORIA = 8;
THE_EMISSARY_WINDURST = 9;
THE_FOUR_MUSKETEERS = 10;
TO_THE_FORSAKEN_MINES = 11;
JEUNO = 12;
MAGICITE_BASTOK = 13;
DARKNESS_RISING = 14;
XARCABARD,_LAND_OF_TRUTHS = 15;
RETURN_OF_THE_TALEKEEPER = 16;
THE_PIRATE_S_COVE = 17;
THE_FINAL_IMAGE = 18;
ON_MY_WAY = 19;
THE_CHAINS_THAT_BIND_US = 20;
ENTER_THE_TALEKEEPER = 21;
THE_SALT_OF_THE_EARTH = 22;
WHERE_TWO_PATHS_CONVERGE = 23;

-----------------------------------
--  Windurst
-----------------------------------
	
THE_HORUTOTO_RUINS_EXPERIMENT = 0;
THE_HEART_OF_THE_MATTER = 1;
THE_PRICE_OF_PEACE = 2;
LOST_FOR_WORDS = 3;
A_TESTING_TIME = 4;
THE_THREE_KINGDOMS = 5;
THE_THREE_KINGDOMS_SAN_D_ORIA = 6;
THE_THREE_KINGDOMS_BASTOK = 7;
THE_THREE_KINGDOMS_SAN_D_ORIA = 8;
THE_THREE_KINGDOMS_BASTOK = 9;
TO_EACH_HIS_OWN_RIGHT = 10;
WRITTEN_IN_THE_STARS = 11;
A_NEW_JOURNEY = 12;
MAGICITE = 13;
THE_FINAL_SEAL = 14;
THE_SHADOW_AWAITS = 15;
FULL_MOON_FOUNTAIN = 16;
SAINTLY_INVITATION = 17;
THE_SIXTH_MINISTRY = 18;
AWAKENING_OF_THE_GODS = 19;
VAIN = 20;
THE_JESTER_WHO_D_BE_KING = 21;
DOLL_OF_THE_DEAD = 22;
MOON_READING = 23;