------------------------------------
-- WEAPONSKILL IDs
--
-- Contains readable values for Weaponskill IDs
------------------------------------

------------------------------------
-- H2H
------------------------------------
WEAPONSKILL_COMBO               = 1;
WEAPONSKILL_SHOULDER_TACKLE     = 2;
WEAPONSKILL_ONE_INCH_PUNCH      = 3;
WEAPONSKILL_BACKHAND_BLOW       = 4;
WEAPONSKILL_RAGING_FISTS        = 5;
WEAPONSKILL_SPINNING_ATTACK     = 6;
WEAPONSKILL_HOWLING_FIST        = 7;
WEAPONSKILL_DRAGON_KICK         = 8;
WEAPONSKILL_ASURAN_FISTS        = 9;
WEAPONSKILL_FINAL_HEAVEN        = 10;
WEAPONSKILL_ASCETICS_FURY       = 11;
WEAPONSKILL_STRINGING_PUMMEL    = 12;
WEAPONSKILL_TORNADO_KICK        = 13;
WEAPONSKILL_VICTORY_SMITE       = 14;
WEAPONSKILL_SHIJIN_SPIRAL       = 15;

------------------------------------
-- DAGGER
------------------------------------
WEAPONSKILL_WASP_STING          = 16;
WEAPONSKILL_VIPER_BITE          = 17;
WEAPONSKILL_GUST_SLASH          = 19;
WEAPONSKILL_SHADOWSTICH         = 18;
WEAPONSKILL_CYCLONE             = 20;
WEAPONSKILL_ENERGY_STEAL        = 21;
WEAPONSKILL_ENERGY_DRAIN        = 22;
WEAPONSKILL_DANCING_EDGE        = 23;
WEAPONSKILL_SHARK_BITE          = 24;
WEAPONSKILL_EVISCERATION        = 25;
WEAPONSKILL_MERCY_STROKE        = 26;
WEAPONSKILL_MANDALIC_STAB       = 27;
WEAPONSKILL_MORDANT_RIME        = 28;
WEAPONSKILL_PYRRHIC_KLEOS       = 29;
WEAPONSKILL_AEOLIAN_EDGE        = 30;
WEAPONSKILL_RUDRAS_STROM        = 31;
WEAPONSKILL_EXENTERATOR         = 224;

------------------------------------
-- SWORD
------------------------------------
WEAPONSKILL_FAST_BLADE          = 32;
WEAPONSKILL_BURNING_BLADE       = 33;
WEAPONSKILL_RED_LOTUS_BLADE     = 34;
WEAPONSKILL_FLAT_BLADE          = 35;
WEAPONSKILL_SHINING_BLADE       = 36;
WEAPONSKILL_SERAPH_BLADE        = 37;
WEAPONSKILL_CIRCLE_BLADE        = 38;
WEAPONSKILL_SPIRIT_WITHIN       = 39;
WEAPONSKILL_VORPAL_BLADE        = 40;
WEAPONSKILL_SWIFT_BLADE         = 41;
WEAPONSKILL_SAVAGE_BLADE        = 42;
WEAPONSKILL_KNIGHTS_OF_ROUND    = 43;
WEAPONSKILL_DEATH_BLOSSOM       = 44;
WEAPONSKILL_ATONEMENT           = 45;
WEAPONSKILL_EXPIACION           = 46;
WEAPONSKILL_SANGUINE_BLADE      = 47;
WEAPONSKILL_CHANT_DU_CYGNE      = 225;
WEAPONSKILL_REQUIESCAT          = 226;
WEAPONSKILL_URIEL_BLADE         = 238;
WEAPONSKILL_GLORY_SLASH         = 239;

------------------------------------
-- GREAT SWORD
------------------------------------
WEAPONSKILL_HARD_SLASH          = 48;
WEAPONSKILL_POWER_SLASH         = 49;
WEAPONSKILL_FROSTBITE           = 50;
WEAPONSKILL_FREEZEBITE          = 51;
WEAPONSKILL_SHOCKWAVE           = 52;
WEAPONSKILL_CRESCENT_MOON       = 53;
WEAPONSKILL_SICKLE_MOON         = 54;
WEAPONSKILL_SPINNING_SLASH      = 55;
WEAPONSKILL_GROUND_STRIKE       = 56;
WEAPONSKILL_HERCULEAN_STRIKE    = 58;
WEAPONSKILL_SCOURGE             = 57;
WEAPONSKILL_TORCLEAVER          = 59;
WEAPONSKILL_RESOLUTION          = 60;

------------------------------------
-- AXE
------------------------------------
WEAPONSKILL_RAGING_AXE          = 64;
WEAPONSKILL_SMASH_AXE           = 65;
WEAPONSKILL_GALE_AXE            = 66;
WEAPONSKILL_AVALANCHE_AXE       = 67;
WEAPONSKILL_SPINNING_AXE        = 68;
WEAPONSKILL_RAMPAGE             = 69;
WEAPONSKILL_CALAMITY            = 70;
WEAPONSKILL_MISTRAL_AXE         = 71;
WEAPONSKILL_DECIMATION          = 72;
WEAPONSKILL_ONSLAUGHT           = 73;
WEAPONSKILL_PRIMAL_REND         = 74;
WEAPONSKILL_BORA_AXE            = 75;
WEAPONSKILL_CLOUDSPLITTER       = 76;
WEAPONSKILL_RUINATOR            = 77;

------------------------------------
-- GREAT AXE
------------------------------------
WEAPONSKILL_SHIELD_BREAK        = 80;
WEAPONSKILL_IRON_TEMPEST        = 81;
WEAPONSKILL_STURMWIND           = 82;
WEAPONSKILL_ARMOR_BREAK         = 83;
WEAPONSKILL_KEEN_EDGE           = 84;
WEAPONSKILL_WEAPON_BREAK        = 85;
WEAPONSKILL_RAGING_RUSH         = 86;
WEAPONSKILL_FULL_BREAK          = 87;
WEAPONSKILL_STEEL_CYCLONE       = 88;
WEAPONSKILL_METATRON_TORMENT    = 89;
WEAPONSKILL_KINGS_JUSTICE       = 90;
WEAPONSKILL_FELL_CLEAVE         = 91;
WEAPONSKILL_UKKOS_FURY          = 92;
WEAPONSKILL_UPHEAVAL            = 93;

------------------------------------
-- SCYTHE
------------------------------------
WEAPONSKILL_SLICE               = 96;
WEAPONSKILL_DARK_HARVEST        = 97;
WEAPONSKILL_SHADOW_OF_DEATH     = 98;
WEAPONSKILL_NIGHTMARE_SCYTHE    = 99;
WEAPONSKILL_SPINNING_SCYTHE     = 100;
WEAPONSKILL_VORPAL_SCYTHE       = 101;
WEAPONSKILL_GUILLOTINE          = 102;
WEAPONSKILL_CROSS_REAPER        = 103;
WEAPONSKILL_SPIRAL_HELL         = 104;
WEAPONSKILL_CATASTROPHE         = 105;
WEAPONSKILL_INSURGENCY          = 106;
WEAPONSKILL_INFERNAL_SCYTHE     = 107;
WEAPONSKILL_QUIETUS             = 108;
WEAPONSKILL_ENTROPY             = 109;

------------------------------------
-- POLEARM
------------------------------------
WEAPONSKILL_DOUBLE_THRUST       = 112;
WEAPONSKILL_THUNDER_THRUST      = 113;
WEAPONSKILL_RAIDEN_THRUST       = 114;
WEAPONSKILL_LEG_SWEEP           = 115;
WEAPONSKILL_PENTA_THRUST        = 116;
WEAPONSKILL_VORPAL_THRUST       = 117;
WEAPONSKILL_SKEWER              = 118;
WEAPONSKILL_WHEELING_THRUST     = 119;
WEAPONSKILL_IMPULSE_DIVE        = 120;
WEAPONSKILL_GEIRSKOGUL          = 121;
WEAPONSKILL_DRAKESBANE          = 122;
WEAPONSKILL_SONIC_THRUST        = 123;
WEAPONSKILL_CAMLANNS_TORMENT    = 124;
WEAPONSKILL_STARDIVER           = 125;

------------------------------------
-- KATANA
------------------------------------
WEAPONSKILL_BLADE_RIN           = 128;
WEAPONSKILL_BLADE_RETSU         = 129;
WEAPONSKILL_BLADE_TEKI          = 130;
WEAPONSKILL_BLADE_TO            = 131;
WEAPONSKILL_BLADE_CHI           = 132;
WEAPONSKILL_BLADE_EI            = 133;
WEAPONSKILL_BLADE_JIN           = 134;
WEAOPNSKILL_BLADE_TEN           = 135;
WEAPONSKILL_BLADE_KU            = 136;
WEAPONSKILL_BLADE_METSU         = 137;
WEAPONSKILL_BLADE_KAMU          = 138;
WEAPONSKILL_BLADE_YU            = 139;
WEAPONSKILL_BLADE_HI            = 140;
WEAPONSKILL_BLADE_SHUN          = 141;

------------------------------------
-- GREAT KATANA
------------------------------------
WEAPONSKILL_TACHI_ENPI          = 144;
WEAPONSKILL_TACHI_HOBAKU        = 145;
WEAPONSKILL_TACHI_GOTEN         = 146;
WEAPONSKILL_TACHI_KAGERO        = 147;
WEAPONSKILL_TACHI_JINPU         = 148;
WEAPONSKILL_TACHI_KOKI          = 149;
WEAPONSKILL_TACHI_YUKIKAZE      = 150;
WEAPONSKILL_TACHI_GEKKO         = 151;
WEAPONSKILL_TACHI_KASHA         = 152;
WEAPONSKILL_TACHI_KAITEN        = 153;
WEAPONSKILL_TACHI_RANA          = 154;
WEAPONSKILL_TACHI_AGEHA         = 155;
WEAPONSKILL_TACHI_FUDO          = 156;
WEAPONSKILL_TACHI_SHOHA         = 157;

------------------------------------
-- CLUB
------------------------------------
WEAPONSKILL_SHINING_STRIKE      = 160;
WEAPONSKILL_SERAPH_STRIKE       = 161;
WEAPONSKILL_BRAINSHAKER         = 162;
WEAPONSKILL_STARLIGHT           = 163;
WEAPONSKILL_MOONLIGHT           = 164;
WEAPONSKILL_SKULLBREAKER        = 165;
WEAPONSKILL_TRUE_STRIKE         = 166;
WEAPONSKILL_JUDGMENT            = 167;
WEAPONSKILL_HEXA_STRIKE         = 168;
WEAPONSKILL_BLACK_HALO          = 169;
WEAPONSKILL_RANDGRITH           = 170;
WEAPONSKILL_MYSTIC_BOON         = 171;
WEAPONSKILL_FLASH_NOVA          = 172;
WEAPONSKILL_DAGAN               = 173;
WEAPONSKILL_REALMRAZER          = 174;

------------------------------------
-- STAFF
------------------------------------
WEAPONSKILL_HEAVY_SWING         = 176;
WEAPONSKILL_ROCK_CRUSHER        = 177;
WEAPONSKILL_EARTH_CRUSHER       = 178;
WEAPONSKILL_STARBURST           = 179;
WEAPONSKILL_SUNBURST            = 180;
WEAPONSKILL_SHELL_CRUSHER       = 181;
WEAPONSKILL_FULL_SWING          = 182;
WEAPONSKILL_SPIRIT_TAKER        = 183;
WEAPONSKILL_RETRIBUTION         = 184;
WEAPONSKILL_GATE_OF_TARTARUS    = 185;
WEAPONSKILL_VIDOHUNIR           = 186;
WEAPONSKILL_GARLAND_OF_BLISS    = 187;
WEAPONSKILL_OMNISCIENCE         = 188;
WEAPONSKILL_CATACLYSM           = 189;
WEAPONSKILL_MYRKR               = 190;
WEAPONSKILL_SHATTERSOUL         = 191;
WEAPONSKILL_TARTARUS_TORPOR     = 240;

------------------------------------
-- ARCHERY
------------------------------------
WEAPONSKILL_FLAMING_ARROW       = 192;
WEAPONSKILL_PIERCING_ARROW      = 193;
WEAPONSKILL_DULLING_ARROW       = 194;
WEAPONSKILL_SIDEWINDER          = 196;
WEAPONSKILL_BLAST_ARROW         = 197;
WEAPONSKILL_ARCHING_ARROW       = 198;
WEAPONSKILL_EMPYREAL_ARROW      = 199;
WEAPONSKILL_NAMAS_ARROW         = 200;
WEAPONSKILL_REFULGENT_ARROW     = 201;
WEAPONSKILL_JISHNUS_RADIANCE    = 202;
WEAPONSKILL_APEX_ARROW          = 203;

------------------------------------
-- MARKSMANSHIP
------------------------------------
WEAPONSKILL_HOT_SHOT            = 208;
WEAPONSKILL_SPLIT_SHOT          = 209;
WEAPONSKILL_SNIPER_SHOT         = 210;
WEAPONSKILL_SLUG_SHOT           = 212;
WEAPONSKILL_BLAST_SHOT          = 213;
WEAPONSKILL_HEAVY_SHOT          = 214;
WEAPONSKILL_DETONATOR           = 215;
WEAPONSKILL_CORONACH            = 216;
WEAPONSKILL_TRUEFLIGHT          = 217;
WEAPONSKILL_LEADEN_SALUTE       = 218;
WEAPONSKILL_NUMBING_SHOT        = 219;
WEAPONSKILL_WILDFIRE            = 220;
WEAPONSKILL_LAST_STAND          = 221;
