version: 0.9.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration:
 - Debug
 - Release
platform:
- Win32
- x64
matrix:
  fast_finish: true
shallow_clone: true
init:
- set generator="Visual Studio 16 2019"
- if "%PLATFORM%" == "x64" (set generator="Visual Studio 16 2019 Win64")
before_build:
- cmake . -G %generator%
build:
  project: topaz.sln
  verbosity: normal
  parallel: true
test: off
