version: 0.9.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Debug
platform:
- Win32
- x64
shallow_clone: true
build:
  project: win32\darkstar.sln
  verbosity: minimal
test: off
