FROM ubuntu AS builder

ARG BUILD_DEPS="\
               autoconf\
               automake\
               pkg-config\
               g++-7\
               libmariadbclient-dev\
               libluajit-5.1-dev\
               libzmq3-dev"

RUN apt-get update && \
    apt-get install -y $BUILD_DEPS

COPY win32/ win32/
COPY Makefile.am .
COPY configure.ac .
COPY m4/ m4/
COPY autogen.sh .
COPY gensources.sh .
COPY src/common/ src/common/
COPY src/map/ src/map/
RUN ./autogen.sh
RUN ./configure
RUN make dsgame

FROM ubuntu

ARG RUNTIME_DEPS="\
                  libluajit-5.1\
                  libmariadbclient18\
                  libzmq5"

COPY --from=builder dsgame dsgame

RUN apt-get update && \
    apt-get install -y $RUNTIME_DEPS

COPY scripts/ scripts/
COPY conf/ conf/
COPY compress.dat .
COPY decompress.dat .

COPY docker/ docker/
RUN ./docker/config.sh

EXPOSE 54230

CMD ./dsgame
