FROM ubuntu

ARG DEPS="\
                autoconf\
                automake\
                pkg-config\
                g++-7\
                libmariadbclient-dev\
                libluajit-5.1-dev\
                libzmq3-dev"

RUN apt-get update && \
    apt-get install -y $DEPS && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/build
COPY . .
RUN ./docker/config.sh
RUN ./autogen.sh
RUN ./configure
RUN make
