FROM ubuntu

ARG DEPS="\
                libluajit-5.1\
                libmariadbclient18\
                libzmq5"

RUN apt-get update && \
    apt-get install -y $DEPS && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/build

EXPOSE 54230

CMD ./docker/wait-for-it.sh dsdb:3306 --timeout=0 && ./dsgame
