FROM ubuntu

ARG DEPS="\
                libmariadbclient18\
                libzmq5"

RUN apt-get update && \
    apt-get install -y $DEPS && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/build

EXPOSE 54002

CMD ./dssearch
