FROM ubuntu

ARG DEPS="\
                libmariadbclient18\
                libzmq5"

RUN apt-get update && \
    apt-get install -y $DEPS && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/build

EXPOSE 54001
EXPOSE 54230
EXPOSE 54231

CMD ./dsconnect
