-- Variable TextID   Description text

-- General Texts
ITEM_CANNOT_BE_OBTAINED = 6375; -- You cannot obtain the item <item> come back again after sorting your inventory
          ITEM_OBTAINED = 6378; -- Obtained: <item>
           GIL_OBTAINED = 6379; -- Obtained <number> gil
       KEYITEM_OBTAINED = 6381; -- Obtained key item: <keyitem>

-- Ark Angel death Dialogs.  There's two sets, this one has <prompt>s instead of <Possible Special Code: 00>s
-- The Galka dialog had 3 special codes as opposed to 1 prompt, hence the choice.
           ARK_ANGEL_HM = 7519; -- You shall be defeated by the apathy that plagues you...
           ARK_ANGEL_EV = 7520; -- You shall be overwhelmed by the arrogance that disfigures you...
           ARK_ANGEL_TT = 7521; -- You shall be consumed by the cowardice that binds you...
           ARK_ANGEL_MR = 7522; -- You shall be twisted by the envy that drives you...
           ARK_ANGEL_GK = 7523; -- You shall be burned by the rage that controls you...