@echo off

if "%1"=="" goto usage
if "%2"=="" goto usage

java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Residential_Area\TextIDs.lua %2\dialog-table-000.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Phanauet_Channel\TextIDs.lua %2\dialog-table-001.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Carpenters_Landing\TextIDs.lua %2\dialog-table-002.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Manaclipper\TextIDs.lua %2\dialog-table-003.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bibiki_Bay\TextIDs.lua %2\dialog-table-004.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Uleguerand_Range\TextIDs.lua %2\dialog-table-005.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bearclaw_Pinnacle\TextIDs.lua %2\dialog-table-006.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Attohwa_Chasm\TextIDs.lua %2\dialog-table-007.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Boneyard_Gully\TextIDs.lua %2\dialog-table-008.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\PsoXja\TextIDs.lua %2\dialog-table-009.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Shrouded_Maw\TextIDs.lua %2\dialog-table-010.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Oldton_Movalpolos\TextIDs.lua %2\dialog-table-011.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Newton_Movalpolos\TextIDs.lua %2\dialog-table-012.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Mine_Shaft_2716\TextIDs.lua %2\dialog-table-013.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Hall_of_Transference\TextIDs.lua %2\dialog-table-014.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Konschtat\TextIDs.lua %2\dialog-table-015.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Promyvion-Holla\TextIDs.lua %2\dialog-table-016.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Spire_of_Holla\TextIDs.lua %2\dialog-table-017.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Promyvion-Dem\TextIDs.lua %2\dialog-table-018.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Spire_of_Dem\TextIDs.lua %2\dialog-table-019.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Promyvion-Mea\TextIDs.lua %2\dialog-table-020.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Spire_of_Mea\TextIDs.lua %2\dialog-table-021.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Promyvion-Vahzl\TextIDs.lua %2\dialog-table-022.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Spire_of_Vahzl\TextIDs.lua %2\dialog-table-023.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Lufaise_Meadows\TextIDs.lua %2\dialog-table-024.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Misareaux_Coast\TextIDs.lua %2\dialog-table-025.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Tavnazian_Safehold\TextIDs.lua %2\dialog-table-026.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Phomiuna_Aqueducts\TextIDs.lua %2\dialog-table-027.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Sacrarium\TextIDs.lua %2\dialog-table-028.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Riverne-Site_B01\TextIDs.lua %2\dialog-table-029.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Riverne-Site_A01\TextIDs.lua %2\dialog-table-030.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Monarch_Linn\TextIDs.lua %2\dialog-table-031.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Sealions_Den\TextIDs.lua %2\dialog-table-032.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\AlTaieu\TextIDs.lua %2\dialog-table-033.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Grand_Palace_of_HuXzoi\TextIDs.lua %2\dialog-table-034.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Garden_of_RuHmet\TextIDs.lua %2\dialog-table-035.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Empyreal_Paradox\TextIDs.lua %2\dialog-table-036.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Temenos\TextIDs.lua %2\dialog-table-037.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Apollyon\TextIDs.lua %2\dialog-table-038.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Valkurm\TextIDs.lua %2\dialog-table-039.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Buburimu\TextIDs.lua %2\dialog-table-040.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Qufim\TextIDs.lua %2\dialog-table-041.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Tavnazia\TextIDs.lua %2\dialog-table-042.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Diorama_Abdhaljs-Ghelsba\TextIDs.lua %2\dialog-table-043.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abdhaljs_Isle-Purgonorgo\TextIDs.lua %2\dialog-table-044.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Tahrongi\TextIDs.lua %2\dialog-table-045.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Open_sea_route_to_Al_Zahbi\TextIDs.lua %2\dialog-table-046.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Open_sea_route_to_Mhaura\TextIDs.lua %2\dialog-table-047.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Al_Zahbi\TextIDs.lua %2\dialog-table-048.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\noname\TextIDs.lua %2\dialog-table-049.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Aht_Urhgan_Whitegate\TextIDs.lua %2\dialog-table-050.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Wajaom_Woodlands\TextIDs.lua %2\dialog-table-051.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bhaflau_Thickets\TextIDs.lua %2\dialog-table-052.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Nashmau\TextIDs.lua %2\dialog-table-053.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Arrapago_Reef\TextIDs.lua %2\dialog-table-054.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ilrusi_Atoll\TextIDs.lua %2\dialog-table-055.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Periqia\TextIDs.lua %2\dialog-table-056.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Talacca_Cove\TextIDs.lua %2\dialog-table-057.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Silver_Sea_route_to_Nashmau\TextIDs.lua %2\dialog-table-058.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Silver_Sea_route_to_Al_Zahbi\TextIDs.lua %2\dialog-table-059.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Ashu_Talif\TextIDs.lua %2\dialog-table-060.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Mount_Zhayolm\TextIDs.lua %2\dialog-table-061.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Halvung\TextIDs.lua %2\dialog-table-062.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Lebros_Cavern\TextIDs.lua %2\dialog-table-063.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Navukgo_Execution_Chamber\TextIDs.lua %2\dialog-table-064.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Mamook\TextIDs.lua %2\dialog-table-065.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Mamool_Ja_Training_Grounds\TextIDs.lua %2\dialog-table-066.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Jade_Sepulcher\TextIDs.lua %2\dialog-table-067.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Aydeewa_Subterrane\TextIDs.lua %2\dialog-table-068.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Leujaoam_Sanctum\TextIDs.lua %2\dialog-table-069.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Chocobo_Circuit\TextIDs.lua %2\dialog-table-070.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Colosseum\TextIDs.lua %2\dialog-table-071.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Alzadaal_Undersea_Ruins\TextIDs.lua %2\dialog-table-072.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Zhayolm_Remnants\TextIDs.lua %2\dialog-table-073.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Arrapago_Remnants\TextIDs.lua %2\dialog-table-074.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bhaflau_Remnants\TextIDs.lua %2\dialog-table-075.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Silver_Sea_Remnants\TextIDs.lua %2\dialog-table-076.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Nyzul_Isle\TextIDs.lua %2\dialog-table-077.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Hazhalm_Testing_Grounds\TextIDs.lua %2\dialog-table-078.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Caedarva_Mire\TextIDs.lua %2\dialog-table-079.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Southern_San_dOria_[S]\TextIDs.lua %2\dialog-table-080.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\East_Ronfaure_[S]\TextIDs.lua %2\dialog-table-081.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Jugner_Forest_[S]\TextIDs.lua %2\dialog-table-082.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Vunkerl_Inlet_[S]\TextIDs.lua %2\dialog-table-083.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Batallia_Downs_[S]\TextIDs.lua %2\dialog-table-084.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\La_Vaule_[S]\TextIDs.lua %2\dialog-table-085.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Everbloom_Hollow\TextIDs.lua %2\dialog-table-086.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bastok_Markets_[S]\TextIDs.lua %2\dialog-table-087.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\North_Gustaberg_[S]\TextIDs.lua %2\dialog-table-088.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Grauberg_[S]\TextIDs.lua %2\dialog-table-089.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Pashhow_Marshlands_[S]\TextIDs.lua %2\dialog-table-090.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Rolanberry_Fields_[S]\TextIDs.lua %2\dialog-table-091.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Beadeaux_[S]\TextIDs.lua %2\dialog-table-092.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ruhotz_Silvermines\TextIDs.lua %2\dialog-table-093.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Windurst_Waters_[S]\TextIDs.lua %2\dialog-table-094.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\West_Sarutabaruta_[S]\TextIDs.lua %2\dialog-table-095.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Fort_Karugo-Narugo_[S]\TextIDs.lua %2\dialog-table-096.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Meriphataud_Mountains_[S]\TextIDs.lua %2\dialog-table-097.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Sauromugue_Champaign_[S]\TextIDs.lua %2\dialog-table-098.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Castle_Oztroja_[S]\TextIDs.lua %2\dialog-table-099.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\West_Ronfaure\TextIDs.lua %2\dialog-table-100.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\East_Ronfaure\TextIDs.lua %2\dialog-table-101.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\La_Theine_Plateau\TextIDs.lua %2\dialog-table-102.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Valkurm_Dunes\TextIDs.lua %2\dialog-table-103.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Jugner_Forest\TextIDs.lua %2\dialog-table-104.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Batallia_Downs\TextIDs.lua %2\dialog-table-105.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\North_Gustaberg\TextIDs.lua %2\dialog-table-106.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\South_Gustaberg\TextIDs.lua %2\dialog-table-107.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Konschtat_Highlands\TextIDs.lua %2\dialog-table-108.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Pashhow_Marshlands\TextIDs.lua %2\dialog-table-109.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Rolanberry_Fields\TextIDs.lua %2\dialog-table-110.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Beaucedine_Glacier\TextIDs.lua %2\dialog-table-111.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Xarcabard\TextIDs.lua %2\dialog-table-112.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cape_Teriggan\TextIDs.lua %2\dialog-table-113.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Eastern_Altepa_Desert\TextIDs.lua %2\dialog-table-114.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\West_Sarutabaruta\TextIDs.lua %2\dialog-table-115.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\East_Sarutabaruta\TextIDs.lua %2\dialog-table-116.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Tahrongi_Canyon\TextIDs.lua %2\dialog-table-117.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Buburimu_Peninsula\TextIDs.lua %2\dialog-table-118.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Meriphataud_Mountains\TextIDs.lua %2\dialog-table-119.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Sauromugue_Champaign\TextIDs.lua %2\dialog-table-120.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Sanctuary_of_ZiTah\TextIDs.lua %2\dialog-table-121.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\RoMaeve\TextIDs.lua %2\dialog-table-122.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Yuhtunga_Jungle\TextIDs.lua %2\dialog-table-123.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Yhoator_Jungle\TextIDs.lua %2\dialog-table-124.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Western_Altepa_Desert\TextIDs.lua %2\dialog-table-125.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Qufim_Island\TextIDs.lua %2\dialog-table-126.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Behemoths_Dominion\TextIDs.lua %2\dialog-table-127.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Valley_of_Sorrows\TextIDs.lua %2\dialog-table-128.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ghoyus_Reverie\TextIDs.lua %2\dialog-table-129.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\RuAun_Gardens\TextIDs.lua %2\dialog-table-130.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Mordion_Gaol\TextIDs.lua %2\dialog-table-131.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-La_Theine\TextIDs.lua %2\dialog-table-132.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\noname\TextIDs.lua %2\dialog-table-133.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Beaucedine\TextIDs.lua %2\dialog-table-134.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Xarcabard\TextIDs.lua %2\dialog-table-135.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Beaucedine_Glacier_[S]\TextIDs.lua %2\dialog-table-136.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Xarcabard_[S]\TextIDs.lua %2\dialog-table-137.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Castle_Zvahl_Baileys_[S]\TextIDs.lua %2\dialog-table-138.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Horlais_Peak\TextIDs.lua %2\dialog-table-139.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ghelsba_Outpost\TextIDs.lua %2\dialog-table-140.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Fort_Ghelsba\TextIDs.lua %2\dialog-table-141.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Yughott_Grotto\TextIDs.lua %2\dialog-table-142.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Palborough_Mines\TextIDs.lua %2\dialog-table-143.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Waughroon_Shrine\TextIDs.lua %2\dialog-table-144.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Giddeus\TextIDs.lua %2\dialog-table-145.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Balgas_Dais\TextIDs.lua %2\dialog-table-146.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Beadeaux\TextIDs.lua %2\dialog-table-147.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Qulun_Dome\TextIDs.lua %2\dialog-table-148.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Davoi\TextIDs.lua %2\dialog-table-149.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Monastic_Cavern\TextIDs.lua %2\dialog-table-150.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Castle_Oztroja\TextIDs.lua %2\dialog-table-151.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Altar_Room\TextIDs.lua %2\dialog-table-152.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Boyahda_Tree\TextIDs.lua %2\dialog-table-153.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dragons_Aery\TextIDs.lua %2\dialog-table-154.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Castle_Zvahl_Keep_[S]\TextIDs.lua %2\dialog-table-155.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Throne_Room_[S]\TextIDs.lua %2\dialog-table-156.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Middle_Delkfutts_Tower\TextIDs.lua %2\dialog-table-157.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Upper_Delkfutts_Tower\TextIDs.lua %2\dialog-table-158.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Temple_of_Uggalepih\TextIDs.lua %2\dialog-table-159.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Den_of_Rancor\TextIDs.lua %2\dialog-table-160.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Castle_Zvahl_Baileys\TextIDs.lua %2\dialog-table-161.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Castle_Zvahl_Keep\TextIDs.lua %2\dialog-table-162.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Sacrificial_Chamber\TextIDs.lua %2\dialog-table-163.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Garlaige_Citadel_[S]\TextIDs.lua %2\dialog-table-164.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Throne_Room\TextIDs.lua %2\dialog-table-165.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ranguemont_Pass\TextIDs.lua %2\dialog-table-166.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bostaunieux_Oubliette\TextIDs.lua %2\dialog-table-167.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Chamber_of_Oracles\TextIDs.lua %2\dialog-table-168.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Toraimarai_Canal\TextIDs.lua %2\dialog-table-169.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Full_Moon_Fountain\TextIDs.lua %2\dialog-table-170.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Crawlers_Nest_[S]\TextIDs.lua %2\dialog-table-171.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Zeruhn_Mines\TextIDs.lua %2\dialog-table-172.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Korroloka_Tunnel\TextIDs.lua %2\dialog-table-173.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Kuftal_Tunnel\TextIDs.lua %2\dialog-table-174.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Eldieme_Necropolis_[S]\TextIDs.lua %2\dialog-table-175.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Sea_Serpent_Grotto\TextIDs.lua %2\dialog-table-176.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\VeLugannon_Palace\TextIDs.lua %2\dialog-table-177.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Shrine_of_RuAvitau\TextIDs.lua %2\dialog-table-178.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Stellar_Fulcrum\TextIDs.lua %2\dialog-table-179.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\LaLoff_Amphitheater\TextIDs.lua %2\dialog-table-180.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Celestial_Nexus\TextIDs.lua %2\dialog-table-181.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Walk_of_Echoes\TextIDs.lua %2\dialog-table-182.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Maquette_Abdhaljs_Legion \TextIDs.lua %2\dialog-table-183.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Lower_Delkfutts_Tower\TextIDs.lua %2\dialog-table-184.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-San_dOria\TextIDs.lua %2\dialog-table-185.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Bastok\TextIDs.lua %2\dialog-table-186.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Windurst\TextIDs.lua %2\dialog-table-187.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dynamis-Jeuno\TextIDs.lua %2\dialog-table-188.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\noname\TextIDs.lua %2\dialog-table-189.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\King_Ranperres_Tomb\TextIDs.lua %2\dialog-table-190.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dangruf_Wadi\TextIDs.lua %2\dialog-table-191.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Inner_Horutoto_Ruins\TextIDs.lua %2\dialog-table-192.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ordelles_Caves\TextIDs.lua %2\dialog-table-193.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Outer_Horutoto_Ruins\TextIDs.lua %2\dialog-table-194.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\The_Eldieme_Necropolis\TextIDs.lua %2\dialog-table-195.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Gusgen_Mines\TextIDs.lua %2\dialog-table-196.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Crawlers_Nest\TextIDs.lua %2\dialog-table-197.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Maze_of_Shakhrami\TextIDs.lua %2\dialog-table-198.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\noname\TextIDs.lua %2\dialog-table-199.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Garlaige_Citadel\TextIDs.lua %2\dialog-table-200.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cloister_of_Gales\TextIDs.lua %2\dialog-table-201.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cloister_of_Storms\TextIDs.lua %2\dialog-table-202.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cloister_of_Frost\TextIDs.lua %2\dialog-table-203.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\FeiYin\TextIDs.lua %2\dialog-table-204.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ifrits_Cauldron\TextIDs.lua %2\dialog-table-205.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\QuBia_Arena\TextIDs.lua %2\dialog-table-206.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cloister_of_Flames\TextIDs.lua %2\dialog-table-207.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Quicksand_Caves\TextIDs.lua %2\dialog-table-208.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cloister_of_Tremors\TextIDs.lua %2\dialog-table-209.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\noname\TextIDs.lua %2\dialog-table-210.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cloister_of_Tides\TextIDs.lua %2\dialog-table-211.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Gustav_Tunnel\TextIDs.lua %2\dialog-table-212.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Labyrinth_of_Onzozo\TextIDs.lua %2\dialog-table-213.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Residential_Area\TextIDs.lua %2\dialog-table-214.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Attohwa\TextIDs.lua %2\dialog-table-215.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Misareaux\TextIDs.lua %2\dialog-table-216.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Vunkerl\TextIDs.lua %2\dialog-table-217.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Altepa\TextIDs.lua %2\dialog-table-218.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\nonanme\TextIDs.lua %2\dialog-table-219.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ship_bound_for_Selbina\TextIDs.lua %2\dialog-table-220.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ship_bound_for_Mhaura\TextIDs.lua %2\dialog-table-221.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Provenance\TextIDs.lua %2\dialog-table-222.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\San_dOria-Jeuno_Airship\TextIDs.lua %2\dialog-table-223.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bastok-Jeuno_Airship\TextIDs.lua %2\dialog-table-224.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Windurst-Jeuno_Airship\TextIDs.lua %2\dialog-table-225.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Kazham-Jeuno_Airship\TextIDs.lua %2\dialog-table-226.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ship_bound_for_Selbina\TextIDs.lua %2\dialog-table-227.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ship_bound_for_Mhaura\TextIDs.lua %2\dialog-table-228.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\noname\TextIDs.lua %2\dialog-table-229.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Southern_San_dOria\TextIDs.lua %2\dialog-table-230.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Northern_San_dOria\TextIDs.lua %2\dialog-table-231.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Port_San_dOria\TextIDs.lua %2\dialog-table-232.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Chateau_dOraguille\TextIDs.lua %2\dialog-table-233.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bastok_Mines\TextIDs.lua %2\dialog-table-234.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Bastok_Markets\TextIDs.lua %2\dialog-table-235.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Port_Bastok\TextIDs.lua %2\dialog-table-236.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Metalworks\TextIDs.lua %2\dialog-table-237.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Windurst_Waters\TextIDs.lua %2\dialog-table-238.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Windurst_Walls\TextIDs.lua %2\dialog-table-239.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Port_Windurst\TextIDs.lua %2\dialog-table-240.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Windurst_Woods\TextIDs.lua %2\dialog-table-241.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Heavens_Tower\TextIDs.lua %2\dialog-table-242.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\RuLude_Gardens\TextIDs.lua %2\dialog-table-243.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Upper_Jeuno\TextIDs.lua %2\dialog-table-244.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Lower_Jeuno\TextIDs.lua %2\dialog-table-245.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Port_Jeuno\TextIDs.lua %2\dialog-table-246.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Rabao\TextIDs.lua %2\dialog-table-247.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Selbina\TextIDs.lua %2\dialog-table-248.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Mhaura\TextIDs.lua %2\dialog-table-249.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Kazham\TextIDs.lua %2\dialog-table-250.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Hall_of_the_Gods\TextIDs.lua %2\dialog-table-251.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Norg\TextIDs.lua %2\dialog-table-252.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Uleguerand\TextIDs.lua %2\dialog-table-253.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Grauberg\TextIDs.lua %2\dialog-table-254.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Abyssea-Empyreal_Paradox\TextIDs.lua %2\dialog-table-255.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Western_Adoulin\TextIDs.lua %2\dialog-table-256.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Eastern_Adoulin\TextIDs.lua %2\dialog-table-257.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Rala_Waterways\TextIDs.lua %2\dialog-table-258.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Rala_Waterways_U\TextIDs.lua %2\dialog-table-259.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Yahse_Hunting_Grounds\TextIDs.lua %2\dialog-table-260.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Ceizak_Battlegrounds\TextIDs.lua %2\dialog-table-261.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Foret_de_Hennetiel\TextIDs.lua %2\dialog-table-262.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Yorcia_Weald\TextIDs.lua %2\dialog-table-263.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Yorcia_Weald_U\TextIDs.lua %2\dialog-table-264.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Morimar_Basalt_Fields\TextIDs.lua %2\dialog-table-265.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Marjami_Ravine\TextIDs.lua %2\dialog-table-266.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Kamihr_Drifts\TextIDs.lua %2\dialog-table-267.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Sih_Gates\TextIDs.lua %2\dialog-table-268.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Moh_Gates\TextIDs.lua %2\dialog-table-269.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cirdas_Caverns\TextIDs.lua %2\dialog-table-270.xml
java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Cirdas_Caverns_U\TextIDs.lua %2\dialog-table-271.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Dho_Gates\TextIDs.lua %2\dialog-table-272.xml
REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Woh_Gates\TextIDs.lua %2\dialog-table-273.xml

java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Mog_Garden\TextIDs.lua %2\dialog-table-280.xml

REM java -cp "." DarkstarTextIdUpdate %1\scripts\zones\Mog_House\TextIDs.lua %2\dialog-table-285.xml

goto exit

:usage
echo "usage: DarkstarNpcIdUpdate.bat <DarkStarRootDir> <POLUtilsDumpRootDir> (Use mass-extractor.exe)"

:exit