---------------------------------------------
-- Cyclonic_Turmoil
-- Deals Wind damage in an area of effect. Additional effect: Knockback & Dispel
-- Notes: Dispels multiple buffs.  Wipes shadows.
---------------------------------------------
