@ECHO OFF
forfiles /M abilities*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M bcnm_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M blue_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M conquest*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M exp*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M fishing*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M guild*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M item_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M merits*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M mob_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M nm_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M npc_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M pet_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M server_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M skill*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M spell_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M status_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M synth_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M traits*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M transport*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M treasure_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M triggers*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M water_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M weapon_*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M zone*.sql /D %date:~0,10% /C "cmd /c mysql dspdb -h localhost -u bope -pbope < @FILE"
forfiles /M audit_*.sql /D %date:~0,10% /C "cmd /c ECHO Linkshell.. @fname needs updated"
forfiles /M linkshells*.sql /D %date:~0,10% /C "cmd /c ECHO Linkshell.. @fname needs updated"
forfiles /M Char*.sql /D %date:~0,10% /C "cmd /c ECHO Char table.. @fname needs updated"
pause